# Azure Devops Pipelines

trigger:
- master
- releases/*
- develop
- feature/*

jobs:

- job: 'TestLinux'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27-x64:
        python.version: '2.7'
        python.architecture: 'x64'
      Python35-x64:
        python.version: '3.5'
        python.architecture: 'x64'
      Python36-x64:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37-x64:
        python.version: '3.7'
        python.architecture: 'x64'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      pip install pytest pytest-cov mock scipy
      pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov pyefd --cov-report term-missing
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'PublishArtifact'
  dependsOn: 'TestLinux'
  variables:
    python.version: '3.6'
    python.architecture: 'x64'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'

  - script: python -m pip install --upgrade pip && pip install -U setuptools wheel
    displayName: 'Install Python dependencies'

  - script: python setup.py sdist bdist_wheel --universal
    displayName: 'Build sdist and bdist_wheel'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dist'
    inputs:
      PathtoPublish: dist
      ArtifactName: 'dist'
